### ISSUE TITLE
Searching and sorting improvements

### ISSUE THREAD

**Issue by ergo** [bromix/plugin.video.youtube#294] opened 2015-06-18 19:28 UTC
Hello,

I was wondering if there is a way to use youtube filter functionality?
Youtube provides following filters and it would be great to allow user to use them, because right now if someone searches for lets say "trailers" the resultset is not really a very good one if one cant request youtube to order them by newest etc.

List of filters:

**Upload date**
* Last hour
* Today
* This week
* This month
* This year 

**Type**
* Video
* Channel
* Playlist
* Movie
* Show 

**Duration**
* Short (< 4 minutes)
* Long (> 20 minutes) 

**Features**
* 4K
* HD
* Subtitles/CC
* Creative Commons
* 3D
* Live
* Purchased
* 360° 

**Sort by**
* Relevance
* Upload date
* View count
* Rating

**Comment by bromix** [comment] 2015-06-18 20:08
Duplicate of issue #97

**Comment by bromix** [comment] 2015-07-15 16:58
I close this one because if #97

**Closed by bromix** 2015-07-15 16:58 UTC
